### ISSUE TITLE
Doesn't work for arrays

### ISSUE THREAD

**Issue by gustavotoyota** [KurtGokhan/tsschema#1]
![Screenshot from 2024-03-15 09-31-00](https://github.com/KurtGokhan/tsschema/assets/11639451/48bcaa26-ddfa-40df-b64c-62b75de8a20c)

![Screenshot from 2024-03-15 09-29-59](https://github.com/KurtGokhan/tsschema/assets/11639451/c294ebb8-d668-43e4-bff5-39842b3cbec8)

**Comment by KurtGokhan** [comment]
Issue solved with v1.3.0
