### ISSUE TITLE
Update typescript-json-schema?

### ISSUE THREAD

**Issue by djMax** [KurtGokhan/tsschema#2]
I love this extension, and I'm really surprised more people haven't installed it! I noticed some TS constructs don't work in this extension but work fine in the latest typescript-json-schema. Would you be able to update that to ^0.63.0? I can make a PR if you'd like.

**Comment by KurtGokhan** [comment]
I will try to bring everything up to date today.

**Comment by KurtGokhan** [comment]
Issue solved with v1.3.0
